### ISSUE TITLE
[Feature Request] Spooky Nickname Changer

### ISSUE THREAD

**Issue by jodth07** [discord-python/hacktoberbot#10]
Create a new feature for the bot called `halloweenify`. This is a version of our `hiphopify` feature, except it works a bit differently.
* Instead of being a moderation tool, the command can only be invoked upon yourself.
* When invoked, it randomly changes your own name to a scary spooky halloween name, and delivers a hiphopify-esque embed with a picture.
* The nickname change is not enforced in any way, and **there is no halloweenify-prison**.

If you're not sure what hiphopify is, here is an example of how the embed looks:
![image](https://user-images.githubusercontent.com/2098517/46559511-e127fa80-c8f0-11e8-8098-1919e1b4c94b.png)

- [ ] Scrape some spooky names from the web, along with accompanying pictures.
- [ ] Store these in a JSON file (or a similar data format)
- [ ] Implement a `!halloweenify` command that changes the invokers name to one of these names.
- [ ] Build and deliver an embed like the one shown above with a picture of the character whose name you've adopted.

**Comment by markylon** [comment]
I'll tackle this, could you just confirm that https://www.empireonline.com/movies/features/best-horror-characters/ is a good source for the spooky names and images?

**Comment by markylon** [comment]
Also, where do you suggest to store the JSON file?

**Comment by heavysaturn** [comment]
okay, marking this as work in progress as @markylon has claimed it.

**Comment by heavysaturn** [comment]
solved in #34
