### ISSUE TITLE
[Feature Request] Candy collection game

### ISSUE THREAD

**Issue by jodth07** [discord-python/hacktoberbot#11]
In the spirit of halloween, let's go Trick or Treat in a form of a game:
This game will be a feature of the bot, where it will post a candy on main chat as an emoji (may want to use python emoji module, or other emoji sources or thumbnail image modules). 

The first person who react to the emji will gets a candy if it's a treat, or a candy eating pumpkin that eats 5 to 10 of their candies. (Higher frequency of candies than pumpkin).

![screen shot 2018-10-07 at 12 50 33 pm](https://user-images.githubusercontent.com/8127555/46584295-ad072380-ca2f-11e8-8db6-97a9066eb307.png)

You have picked up a candy eating pumpkin. the pumpkin eats 5 ( if less than five, remaining/all) of your candies. [story can vary]

- [ ] Source of candy emojies
- [ ] contains different kind of halloween candy
- [ ] includes trick or treat
- [ ] need to store candy in user's

**Comment by sco1** [comment]
There needs to be some more details about what this game is about. What *is* the game? What are the objectives? How to people play?

**Comment by heavysaturn** [comment]
We've discussed this a bit internally and come up with an implementation that might work. I will create a new issue for it, for the sake of clarity. #26
