### ISSUE TITLE
GitHub Pull Request template

### ISSUE THREAD

**Issue by GhostofGoes** [discord-python/hacktoberbot#15]
Add a template for pull requests. Ideally, this would have a checklist of the basic things the PR should have, and sections to fill in with content.

[GitHub's documentation](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)
[Examples of templates](https://github.com/stevemao/github-issue-templates)

**Comment by IgnatiusFlo** [comment]
Hello, I'm very much a beginner but I'll have a stab at this.

**Comment by IgnatiusFlo** [comment]
I have created a generic form for PRs. Could you let me know what specific criteria you'd like met for each tick box?

Cheers

**Comment by jos-b** [comment]
Added in #49
