### ISSUE TITLE
GitHub Issue templates

### ISSUE THREAD

**Issue by GhostofGoes** [discord-python/hacktoberbot#16]
Add templates for new issues.
* [ ] Bug reports
* [ ] Feature requests

These should be created in `.github/ISSUE_TEMPLATES`, and named `<template-name>.md`.

[GitHub's documentation](https://help.github.com/articles/creating-issue-templates-for-your-repository/)
[Examples of templates](https://github.com/stevemao/github-issue-templates)

**Comment by danieldeveloper001** [comment]
@GhostofGoes, please, take a look at the templates on issue #19 and let me know if you like them!

**Comment by danieldeveloper001** [comment]
P.S.: I'm using the template myself to open the pull request :stuck_out_tongue:

**Comment by heavysaturn** [comment]
Solved in #19
