### ISSUE TITLE
[Feature Request] Spooky bot reactions!

### ISSUE THREAD

**Issue by heavysaturn** [discord-python/hacktoberbot#27]
When someone in the channel uses the word spooky, the bot should automatically react to the message with a :ghost:.

## Implementation details

- [ ] Make a new cog for the bot
- [ ] In this cog, implement the `on_message` event, which will trigger every time the bot sees a new message.
- [ ] If the message contents contain the word `spooky` (or other halloween themed words), add an appropriate reaction. 

## Additional information
Please feel free to improvise and add more trigger words and reactions that fit the theme. Skeletons and :skull:, maybe?

**Comment by martmists** [comment]
I'll see if I can implement this today

spooky -> 👻
skeleton/doot -> 💀
pumpkin/halloween -> 🎃

feel free to suggest more, I'll implement as many as I can

**Comment by heavysaturn** [comment]
@martmists Maybe it'd be better if you handled one of the more difficult issues? this is way too easy for you, dude.

**Comment by hundredrab** [comment]
Hi, could I take this up?
