### ISSUE TITLE
[Feature Request] Interesting Halloween facts

### ISSUE THREAD

**Issue by jodth07** [discord-python/hacktoberbot#32]
Have you ever wanted to get random interesting (Maybe) facts about Halloween, the month of October and other related things?

## General info

Well, you have come to the right place. Instead of looking for these facts, you get to create a list containing those facts that can be posted by the bot, as in:
`Your daily random information about Halloween:  Did you know that Halloween's  origins date back to the ancient Celtic festival of Samhain?`.
Other fun spooky facts are also welcomed. 

This information can also be accessed via the bot command !hallofacts.

## Implementation details

- [ ] Write the bot command to access hallofacts
- [ ] Add the command to our README.md
- [ ] get a list of random interesting facts about Halloween
- [ ] post random facts daily

## Additional information

Provide any additional information or clarifications here.
This PR is for beginners / Intermediate discordPythoners. See also feature #9 for similarities.

**Comment by jodth07** [comment]
you can have it post multiple facts daily, and the command is there just to recall the last fact posted.

**Comment by Rahisulhaque** [comment]
I can do that too!

**Comment by meooow25** [comment]
@Rahisulhaque the PR has been merged. Perhaps you would like to take up another issue.  
This issue should be closed, thanks.

**Comment by jos-b** [comment]
Added in #36
