### ISSUE TITLE
[Feature Request] Logging

### ISSUE THREAD

**Issue by sco1** [discord-python/hacktoberbot#5]
Logging events and errors while an application is running is extremely useful for tasks like diagnosing issues and analyzing usage patterns. 

Python's [`logging` library](https://docs.python.org/3/library/logging.html) provides a great built-in tool to enable application-level logging. Python's documentation also offers a [comprehensive series of tutorials](https://docs.python.org/3/howto/logging.html#logging-basic-tutorial) aimed at users with varying levels of experience.

The proposed feature set includes:

- [ ] Log to a discrete `/log/` folder, whose contents are not tracked by Git
- [ ] Single `logger` configuration and initialization
- [ ] Log bot events (e.g. login)
- [ ] Log events in all cogs and helper utilities at the appropriate level (`info`, `debug`, etc.)
- [ ] Log errors & warnings

**Comment by ninexball** [comment]
I am interested in doing this

**Comment by heavysaturn** [comment]
it's all yours!

**Comment by heavysaturn** [comment]
Solved in #22
