### ISSUE TITLE
[Feature Request] Random scary movie generator

### ISSUE THREAD

**Issue by jodth07** [discord-python/hacktoberbot#9]
The goal of this tasks is to access the OMDB API, and find movies that are scary / spooky, and make them searchable/accessible via the bot.
- [ ] generate a random movie tag scary and/or spooky
- [ ] should contain, title, main actors and image, and year
- [ ] should also link to OMDB
- [ ] Perhaps also a spookiness/scary rating

**Comment by akashsara** [comment]
Can I take this?

**Comment by rgables** [comment]
I'd like to take a crack at this

**Comment by jodth07** [comment]
have at it @rgables

**Comment by heavysaturn** [comment]
solved in #23
